- alias: Tristal - Away
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.tristal
    from: 'home'
    to: 'not_home'
  actions:
    service: input_boolean.turn_on
    entity_id: input_boolean.tristal_awaymode
